apiVersion: v1
kind: Service
metadata:
  name: geolocation-svc
  labels:
    app: geolocation
spec:
  ports:
  - name: geolocation
    port: 8089
    targetPort: 8082
  selector:
    app: geolocation
  type: NodePort
